# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/ownCloud/work/cpp/floquetwtd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/ownCloud/work/cpp/floquetwtd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/ownCloud/work/cpp/floquetwtd/CMakeFiles /home/david/ownCloud/work/cpp/floquetwtd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/ownCloud/work/cpp/floquetwtd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named floquetwtd

# Build rule for target.
floquetwtd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 floquetwtd
.PHONY : floquetwtd

# fast build rule for target.
floquetwtd/fast:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/build
.PHONY : floquetwtd/fast

glfixed.o: glfixed.c.o

.PHONY : glfixed.o

# target to build an object file
glfixed.c.o:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/glfixed.c.o
.PHONY : glfixed.c.o

glfixed.i: glfixed.c.i

.PHONY : glfixed.i

# target to preprocess a source file
glfixed.c.i:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/glfixed.c.i
.PHONY : glfixed.c.i

glfixed.s: glfixed.c.s

.PHONY : glfixed.s

# target to generate assembly for a file
glfixed.c.s:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/glfixed.c.s
.PHONY : glfixed.c.s

main.o: main.cxx.o

.PHONY : main.o

# target to build an object file
main.cxx.o:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/main.cxx.o
.PHONY : main.cxx.o

main.i: main.cxx.i

.PHONY : main.i

# target to preprocess a source file
main.cxx.i:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/main.cxx.i
.PHONY : main.cxx.i

main.s: main.cxx.s

.PHONY : main.s

# target to generate assembly for a file
main.cxx.s:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/main.cxx.s
.PHONY : main.cxx.s

ses.o: ses.cxx.o

.PHONY : ses.o

# target to build an object file
ses.cxx.o:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/ses.cxx.o
.PHONY : ses.cxx.o

ses.i: ses.cxx.i

.PHONY : ses.i

# target to preprocess a source file
ses.cxx.i:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/ses.cxx.i
.PHONY : ses.cxx.i

ses.s: ses.cxx.s

.PHONY : ses.s

# target to generate assembly for a file
ses.cxx.s:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/ses.cxx.s
.PHONY : ses.cxx.s

wtd.o: wtd.cxx.o

.PHONY : wtd.o

# target to build an object file
wtd.cxx.o:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/wtd.cxx.o
.PHONY : wtd.cxx.o

wtd.i: wtd.cxx.i

.PHONY : wtd.i

# target to preprocess a source file
wtd.cxx.i:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/wtd.cxx.i
.PHONY : wtd.cxx.i

wtd.s: wtd.cxx.s

.PHONY : wtd.s

# target to generate assembly for a file
wtd.cxx.s:
	$(MAKE) -f CMakeFiles/floquetwtd.dir/build.make CMakeFiles/floquetwtd.dir/wtd.cxx.s
.PHONY : wtd.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... floquetwtd"
	@echo "... glfixed.o"
	@echo "... glfixed.i"
	@echo "... glfixed.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... ses.o"
	@echo "... ses.i"
	@echo "... ses.s"
	@echo "... wtd.o"
	@echo "... wtd.i"
	@echo "... wtd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

